name: first
on: push
jobs:
  first-job:
    name:  First Job
    runs-on: ubuntu-latest
    steps:
    - name: Print date
      run: date
    
  second-job:
    name: Second Job
    runs-on: windows-latest
    steps:
    - name: Print date
      run: "Get-Date"
      
  third-job:
    name: Third Job
    runs-on: macos-latest
    steps:
    - name: Print date
      run: date

  fourth-job:
    name: Fourth Job
    runs-on: ubuntu-latest
    needs: [first-job, second-job, third-job]
    steps:
    - name: Print the date
      run: date
